### ISSUE TITLE
Use nickname rather than usename if available

### ISSUE THREAD

**Issue by rasher** [andipaetzold/tttt-discord#24]
It would be great if the bot used the nickname on the server, rather than the username when announcing an @-mentioned rider. That way the rider won't have to globally change their username, visible on all servers they use.

As far as I can tell, this can be done using `.displayName` on `GuildMember`, though I don't 100% see how to get there from the client instance - I guess some context to the current Guild is needed. I'm sure you understand better than me.

**Comment by andipaetzold** [comment]
Hey @rasher 

thanks for bringing this up!

I actually wanted to do this but it seems like I forgot about it. ¯\_(ツ)_/¯ 
I prepared a PR and will probably merge it tomorrow after some more testing.

**Comment by andipaetzold** [comment]
@rasher 

The change is live. Now, the users should be announced with their nickname.
